---
pagetitle: GGE ODYSSEY
title: <center>Odyssey Mission Statement
---

<br><br>
The UC Davis Graduate Group in Ecology’s (GGE) “The Odyssey” is an immersive experience, which introduces incoming graduate students to the resources and opportunities available to them as GGE students, and provides a first introduction to their cohort and the GGE community at large. 
<br><br>
The foremost goal of the GGE is to provide world class training to the next generation of ecologists. To this end, The Odyssey introduces first year students to some of the places and people critical to success within the GGE. The Odyssey provides an informal atmosphere where students learn about the University of California Natural Reserve System, ongoing research, and meet current GGE faculty and staff. Cultivating relationships with these places and individuals from the onset makes it easier for students to feel comfortable seeking guidance and support early on in their academic career.
<br><br>
A strong community is complementary to professional success, and as such The Odyssey serves as a chance to build a supportive collegial and social atmosphere that is carried throughout a student's graduate career. During The Odyssey, returning students and staff strive to create an atmosphere in line with the UC Davis Principles of Community, which “confronts and rejects all manifestations of discrimination.” We hope this atmosphere mirrors the larger community that waits for new students back in Davis.  Further, due to the diverse background of incoming students, The Odyssey seeks to help participants minimize/shed anxiety created by the “imposter syndrome” by exploring the diversity of backgrounds and skills within the GGE and affirming the collegial attitude among GGE students and faculty through an interdisciplinary experience that could not be led by any single instructor. Regardless of if you want to find a research collaborator, a dance party, a good hiking trail, or the best potlucks in town, we want first year students to leave the Odyssey feeling prepared, supported, and excited for the journey to come.